- editors/common/codegen.ts
- editors/document-model/editor-initital-state.tsx
- editors/document-model/editor-schema.tsx
- editors/document-model/editor.tsx
- yarn.lock
> Fixes document model initial state validation

- editors/document-model/editor-operation.tsx
- editors/document-model/editor.tsx
- package.json
- yarn.lock
Fixes #13
https://github.com/powerhouse-inc/document-model-libs/assets/5501872/89e3ddcf-ba95-4477-b216-e00ac6775f30
>  Set operation scope on document model

- document-models/document-drive/document-drive.json
- document-models/document-drive/index.ts
- document-models/document-drive/schema.graphql
- document-models/document-drive/src/reducers/drive.ts
- package.json
- test/document-drive/actions.test.ts
- test/document-drive/base.test.ts
- test/document-drive/document-model.test.ts
- test/document-drive/drive.test.ts
- test/document-drive/node.test.ts
- yarn.lock
Fixes #20 
Added changes manually, these will eventually be done with code generation.
> WIP: Add local documentDrive operations

- editors/document-model/editor-schema.tsx
- editors/document-model/editor-state.tsx
- editors/document-model/editor.tsx
- editors/document-model/useSchemaEditor.ts
- added support for local state schema in document-model editor
NOTE: this PR requires a new release from https://github.com/powerhouse-inc/document-model with the latest changes
```json
{
"name": "",
"documentType": "powerhouse/document-model",
"revision": 12,
"created": "2023-12-14T19:02:53.112Z",
"lastModified": "2023-12-14T19:06:38.109Z",
"attachments": {},
"state": {
"global": {
"id": "budget",
"name": "MyDocument",
"extension": "phxyz",
"description": "",
"author": {
"name": "powerhouse",
"website": "https://www.powerhouse.inc/"
},
"specifications": [
{
"version": 1,
"changeLog": [],
"state": {
"global": {
"schema": "type MyDocumentState {\n\tcolor: String!\n    isMainDoc: Boolean\n}",
"initialValue": "{\"color\":\"yellow\",\"isMainDoc\":false}",
"examples": []
},
"local": { …
```
> feat: added support for local state schema in document-model editor

- editors/common/json-editor.tsx
- editors/json/editor.tsx
- Added `onBlur` prop to `JSONEditor`
> feat: added onBlur prop to JSONEditor

- .storybook/main.ts
- document-models/account-snapshot/src/tests/snapshot.test.ts
- document-models/budget-statement/src/tests/account.test.ts
- document-models/budget-statement/src/tests/audit.test.ts
- document-models/budget-statement/src/tests/base.test.ts
- document-models/budget-statement/src/tests/comment.test.ts
- document-models/budget-statement/src/tests/line-item.test.ts
- document-models/budget-statement/src/tests/vesting.test.ts
- document-models/document-drive/src/tests/drive.test.ts
- document-models/document-drive/src/tests/node.test.ts
- document-models/scope-framework/src/tests/main.test.ts
- package.json
- vite.config.ts
- yarn.lock
We have renamed the `@acaldas/powerhouse` lib to be `@powerhousedao/codegen`
Update the dependency name and references to it.
> feat: use new codegen lib name

- editors/document-model/editor-schema.tsx
> fix: update editor reference

- document-models/document-drive/schema.graphql
- document-models/document-drive/src/reducers/node.ts
- document-models/document-drive/src/tests/base.test.ts
- Added support for document in document Drive addFileOperation
> feat: Added support for document in document Drive addFileOperation

- document-models/document-drive/document-drive.json
- document-models/document-drive/schema.graphql
- document-models/document-drive/src/reducers/drive.ts
- document-models/document-drive/src/reducers/node.ts
- package.json
- yarn.lock
> Added triggers array to document drive local state

- editors/rwa/portfolio.tsx
remove id field from fields priority, as described in https://github.com/powerhouse-inc/design-system/pull/189
> feat: remove id field from fields priority

- document-models/real-world-assets/real-world-assets.json
- document-models/real-world-assets/src/tests/document-model.test.ts
- editors/rwa/index.ts
> feat: fix rwa document name

- editors/rwa/editor.tsx
- package.json
- pnpm-lock.yaml
- enabled support for switchboard link in RWA editor
> NOTE: This PR requires https://github.com/powerhouse-inc/design-system/pull/218
> feat: enabled support for switchboard link in RWA editor

- .commitlintrc.json
- .eslintignore
- .github/workflows/release.yml
- .husky/pre-commit
- .releaserc
- commitlint.config.js
- document-models/real-world-assets/src/tests/transactions.test.ts
- package.json
- pnpm-lock.yaml
> feat: added release ghub action

- .github/workflows/release.yml
- removed build step from release action
> refactor: removed build step from release action

- tailwind.config.ts
> fix: tailwind config

- document-models/real-world-assets/src/reducers/transactions.ts
- editors/rwa/transactions.tsx
- package.json
- pnpm-lock.yaml
treat cash balance change as an input to avoid stale state errors.
> feat: treat cash balance change as input

- editors/document-model/editor-initital-state.tsx
- Added auto format initial state when mount editor component
> feat: format initial state on mount

- package.json
The package.json exports seem to have gotten mixed up in a bad merge.
> chore: fix exports

- .storybook/preview-body.html
- tailwind.config.ts
- Generate scoped styles
https://discord.com/channels/815917281728659516/1171481967242518620/1220377481727447040
> feat: fix tailwind class conflicts

- .github/workflows/release.yml
- .releaserc
- enable arbitrum release branch
> feat: enable arbitrum release branch

- document-models/real-world-assets/src/reducers/transactions.ts
- editors/rwa/portfolio.tsx
- editors/rwa/transactions.tsx
- package.json
- pnpm-lock.yaml
> feat: add cash asset row

- package.json
- pnpm-lock.yaml
> feat: update document-model lib version

- editors/utils/reducer.ts
- re-enable onErrorCallback with new operations error prop
> feat: re-enable onErrorCallback with new operations error prop

- package.json
- pnpm-lock.yaml
bump design system to integrate latest QA updates.
> feat: integrate QA updates

- editors/rwa/editor.tsx
- editors/rwa/other/accounts.tsx
- editors/rwa/other/fixed-income-types.tsx
- editors/rwa/other/service-provider-fee-types.tsx
- editors/rwa/other/spvs.tsx
- editors/rwa/portfolio.tsx
- editors/rwa/transactions.tsx
- package.json
- pnpm-lock.yaml
pass allow list props down from connect app to editor components.
> feat: add allow list props to rwa document editors

- package.json
- pnpm-lock.yaml
bump design system
I also noticed that we had react-aria-components in both dev dependencies and dependencies so I removed the dev dependencies one as it is redundant. we should change it to be a peer dependency at some point.
> feat: integrate allow scroll and search in rwa dropdowns

- editors/rwa/editor.tsx
- editors/rwa/other/accounts.tsx
- editors/rwa/other/fixed-income-types.tsx
- editors/rwa/other/service-provider-fee-types.tsx
- editors/rwa/other/spvs.tsx
- editors/rwa/portfolio.tsx
- editors/rwa/transactions.tsx
- package.json
- pnpm-lock.yaml
bump design system to integrate allow create other items from item forms (rwa)
pass new create item props to components
> feat: allow item creation from other forms

- document-models/budget-statement/src/tests/audit.test.ts
- package.json
- pnpm-lock.yaml
> feat: update-document-model ver

- package.json
- pnpm-lock.yaml
> feat: update document-model 1.5.0

- editors/rwa/transactions.tsx
- package.json
- pnpm-lock.yaml
fix service provider id not being included in input
bump design system
> feat: qa updates 6

- document-models/real-world-assets/src/_utils/validators/transactions.ts
- document-models/real-world-assets/src/constants.ts
- document-models/real-world-assets/src/reducers/transactions.ts
- document-models/real-world-assets/src/tests/calculations.test.ts
- document-models/real-world-assets/src/tests/diff.test.ts
- document-models/real-world-assets/src/tests/transactions.test.ts
- document-models/real-world-assets/src/tests/validators.test.ts
add unit tests for transaction operations that affect the portfolio. Check that the values balance.
> feat: add calculation unit tests

- document-models/real-world-assets/src/_utils/generators.ts
Add a utility function for adding computed current value of fixed income assets to a document.
The function takes an RWA document and returns an updated copy of the document which has the `currentValue` field added to fixed income assets in the state. The `currentDate` argument is optional — if omitted the current date on the machine is used.
This function uses the `calculateCurrentValue` function to compute these values. This function is still WIP while I work out the details with teep and will change. However, the api for this utility function will not change. Switchboard implementation can begin.
> feat: add document with current values generator

- document-models/real-world-assets/src/_utils/calculations.ts
do not calculate current value if the asset has already expired.
> feat: add date check

- document-models/document-drive/src/reducers/drive.ts
- fix remove drive listener reducer
> fix: remove listener
